apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: backend
  namespace: backend
spec:
  interval: 5m
  url: ssh://git@github.com/suhyeonXYZ/ABC-shoppingmall-deployment
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: backend-app
  namespace: backend
spec:
  interval: 10m
  targetNamespace: backend
  sourceRef:
    kind: GitRepository
    name: backend
  path: "./backend/base"
  prune: true
  timeout: 1m