apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: backend-kustomization 
  namespace: backend           
spec:
  suspend: false
  resources:
    - rollout.yaml
    - keda.yaml
    - service-active.yaml
    - service-preview.yaml
    - ingress.yaml
