apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend-rollout
  namespace: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
      version: canary
  template:
    metadata:
      labels:
        app: backend
        version: canary
    spec:
      containers:
      - name: backend
        image: 983460235393.dkr.ecr.ap-northeast-2.amazonaws.com/ssh-backend:0.1.0
        ports:
        - containerPort: 8000
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8000"
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
  strategy:
    canary:
      steps:
      - setWeight: 20         # 트래픽 20%를 canary에 전달
      - pause: {duration: 10s} # 10초 대기 후 다음 단계 진행
      - setWeight: 50
      - pause: {duration: 10s}
      - setWeight: 100        # 100% 전환
      - pause: {}
      trafficRouting:
        ingress:
          name: backend-ingress
          serviceName: backend-active
          servicePort: 80